apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  labels:
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: cluster
type: kubernetes.io/service-account-token
stringData:
  dummy: value
