apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: nginx 
    repo: https://helm.nginx.com/stable
    version: 0.4.1
    valuesFile: values.yaml
