apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: hello-world
    repo: https://helm.github.io/examples
    version: 1.16.0
    valuesFile: values.yaml
