apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: nms-acm 
    repo: https://helm.nginx.com/stable
    version: 1.6.0
    valuesFile: values.yaml
